services:
  db:
    image: mysql:8.2.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"

  rails: &rails
    build: .
    image: backend_image:latest
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    working_dir: /rails
    stdin_open: true
    tty: true
    environment:
      DB_USER: root
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_TEST_NAME: ${DB_TEST_NAME}
      RAILS_ENV: ${RAILS_ENV}
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      REDIS_URL: redis://redis:6379/0

  runner:
    <<: *rails
    command: /bin/bash
    profiles:
      - manual

  redis:
    image: redis:7.0
    ports:
      - "6379:6379"

  sidekiq:
    <<: *rails
    command: bundle exec sidekiq
    ports:
      - "3001:3001"
